#!/usr/bin/env python3

from sys import argv


try:
    value = argv[1]
    ttype = argv[2]
    print('{} {}'.format(value, ttype))
except:
    print('usage: Treasure #[value] [coin/gems/art/exotic')
