#!/usr/bin/env python

from sys import argv
from random import randint

def edifice(place):
    location = {}
    location['rural'] = ['Farmhouse', 'Barn', 'Shack']
    location['urban'] = ['Police station', 'Fire station', 'Grocery Store', 'Bank', 'Office Complex', 'Factory',
                        'Warehouse', 'Office Complex']
    location['any'] = ['Residence', 'Gas station', 'Grocery Store', 'Transit station', 'Gun store', 'Hardware store',
                        'Restaurant', 'Burned wreckage', 'Demolished rubble', 'Empty lot with a hidden trap door']
    if place == 'rural':
        return location[place][randint(0,len(location[place])-1)]
    elif place == 'urban':
        return location[place][randint(0,len(location[place])-1)]
    else:
        return location['any'][randint(0,len(location['any'])-1)]

try:
    print(edifice(argv[1]))
except IndexError:
    print(edifice('any'))
